# Generated by Django 2.1.7 on 2019-02-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190226_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='kart',
            name='longitude',
        ),
    ]
